---
name: Integration Tests
on:
  pull_request:
    paths:
      - "action.yaml"
      - ".github/workflows/integration-tests.yaml"

jobs:
  test:
    name: Test
    # These permissions are needed to:
    # - Checkout the repo
    # - Use `job-context`: https://github.com/beacon-biosignals/get-workflow-run#permissions
    permissions:
      # actions: read
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        id: workflow
        with:
          workflow-file: integration-tests.yaml
          commit-sha: ${{ github.sha }}
          status: running
      - name: Test
        run: |
          set -x
          [[ "${run_id}" -eq "${{ github.run_id }}" ]] || exit 1
          [[ "${run_attempt}" -eq "${{ github.run_attempt }}" ]] || exit 1
        env:
          run_id: ${{ steps.workflow.outputs.run-id }}
          run_attempt: ${{ steps.workflow.outputs.run-attempt }}
